CentralEstatisticas/CentralEstatisticas/Controllers/SistemaController.cs
using CentralEstatisticas.Business;
using System.Web.Mvc;

namespace CentralEstatisticas.Controllers
{
    public class SistemaController : BaseMvcController
    {
        private SistemaBusiness Business { get; set; }

        public SistemaController()
        {
            Business = new SistemaBusiness();
        }

        public ViewResult Index()
        {
            return View();
        }

        public ViewResult Cadastro(int? idSistema)
        {
            if (idSistema.HasValue)
            {
                Business.Obter(idSistema.Value);
            }
            return View();
        }

        [HttpPost]
        public JsonResult Listar()
        {
            return Json(new { Sistemas = Business.Listar() });
        }

        [HttpPost]
        public JsonResult Salvar(int? idSistema, string empresa, string area, string nome, int idUsuarioResponsavel, bool ativo)
        {
            Business.Salvar(idSistema, empresa, area, nome, idUsuarioResponsavel, ativo);
            return ObterJsonSucessoPadrao();
        }
    }
}

CentralEstatisticas/CentralEstatisticas/Views/Sistema/Cadastro.cshtml
<div class="row">
    <form>
        <input type="hidden" data-hidden-id-sistema/>
        <div class="form-group">
            <label>Empresa</label>
            <input class="form-control" type="text" data-filtro-empresa />
        </div>
        <div class="form-group">
            <label>Área</label>
            <input class="form-control" type="text" data-filtro-area />
        </div>
        <div class="form-group">
            <label>Nome</label>
            <input class="form-control" type="text" data-filtro-area />
        </div>
        <div class="form-group">
            <label>Responsável</label>
            <select class="form-control"></select>
        </div>
        <div class="form-group">
            <label>Ativo?</label>
            <input class="form-control" type="checkbox"/>
        </div>
        <div class="">
            <button class="btn btn-success" type="button" data-salvar>Salvar</button>
            <button class="btn btn-default" type="button" data-voltar>Voltar</button>
        </div>
    </form>
</div>
@section scripts {
    @Scripts.Render("~/bundles/scriptsCadastroSistema")
    <script type="text/javascript">
        var urlSalvar = '@Url.Action("Salvar", "Sistema")';
        var urlLista = '@Url.Action("Index", "Sistema")';
    </script>
}

CentralEstatisticas/CentralEstatisticas/Views/Sistema/Index.cshtml
<div class="row">
    <form>
        <div class="form-group col-md-4">
            <label>Empresa</label>
            <input class="form-control" type="text" data-filtro-empresa />
        </div>
        <div class="form-group col-md-4">
            <label>Área</label>
            <input class="form-control" type="text" data-filtro-area />
        </div>
        <div class="col-md-4">
            <button class="btn btn-default" type="button" data-filtrar>Filtrar</button>
            <button class="btn btn-info" type="button" data-novo>Novo</button>
        </div>
    </form>
</div>
<div class="row">
    <table class="table">
        <thead>
            <tr>
                <th>Empresa</th>
                <th>Área</th>
                <th>Nome</th>
                <th>Responsável</th>
                <th>Editar</th>
            </tr>
        </thead>
        <tbody>
            <tr class="template hide">
                <td data-coluna-empresa></td>
                <td data-coluna-area></td>
                <td data-coluna-nome></td>
                <td data-coluna-responsavel></td>
                <td data-coluna-editar><button data-editar data-id-sistema="" type="button" class="btn btn-info">Editar</button></td>
            </tr>
        </tbody>
    </table>
</div>
@section scripts {
    @Scripts.Render("~/bundles/scriptsListaSistema")
    <script type="text/javascript">
        var urlListar = '@Url.Action("Listar", "Sistema")';
        var urlCadastro = '@Url.Action("Cadastro", "Sistema")';
    </script>
}