CentralEstatisticas/CentralEstatisticas/Controllers/IndicadorTecnicoController.cs
using CentralEstatisticas.Business;
using CentralEstatisticas.Entidades.Dto.IndicadorTecnico;
using CentralEstatisticas.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace CentralEstatisticas.Controllers
{
    public class IndicadorTecnicoController : BaseMvcController
    {
        private IndicadoresTecnicosBusiness Business { get; set; }

        public IndicadorTecnicoController()
        {
            Business = new IndicadoresTecnicosBusiness();
        }

        public ViewResult Index()
        {
            return View(new ListaIndicadoresTecnicosModel
            {
                ListaSistemas = new SistemaBusiness().Listar().Select(s => new SelectListItem { Value = s.Id.ToString(), Text = s.Nome })
            });
        }

        public ViewResult Cadastro(int? idMedicao)
        {
            if (idMedicao.HasValue)
            {
                Business.ObterMedicao(idMedicao.Value);
            }
            return View();
        }

        [HttpPost]
        public JsonResult ListarMedicoes(int idSistema)
        {
            return Json(new { Medicoes = Business.ListarMedicoes(idSistema) });
        }

        [HttpPost]
        public JsonResult SalvarMedicao(int? idMedicao, int idSistema, DateTime data, IEnumerable<IndicadorParaSalvarDto> listaIndicadores)
        {
            Business.SalvarMedicao(idMedicao, idSistema, data, listaIndicadores);
            return ObterJsonSucessoPadrao();
        }

        public JsonResult RemoverMedicao(int idMedicao)
        {
            Business.RemoverMedicao(idMedicao);
            return ObterJsonSucessoPadrao();
        }
    }
}

CentralEstatisticas/CentralEstatisticas/Views/IndicadorTecnico/Cadastro.cshtml
@section scripts {
    @Scripts.Render("~/bundles/scriptsIndicadoresTecnicos")
    <script type="text/javascript">
        var urlSalvarMedicao = '@Url.Action("SalvarMedicao", "IndicadorTecnico")';
    </script>
}

CentralEstatisticas/CentralEstatisticas/Views/IndicadorTecnico/Index.cshtml
@model CentralEstatisticas.Models.ListaIndicadoresTecnicosModel
<div class="row">
    <form>
        <div class="form-group col-md-8">
            <label>Sistema</label>
            <select class="select2" type="text" data-filtro-sistema>
                <option value="">Selecione</option>
                @foreach (var sistema in Model.ListaSistemas)
                {
                    <option value="@sistema.Value">@sistema.Text</option>
                }
            </select>
        </div>
        <div class="col-md-4">
            <button class="btn btn-default" type="button" data-filtrar>Filtrar</button>
            <button class="btn btn-info" type="button" data-novo>Novo</button>
        </div>
    </form>
</div>
<div class="row">
    <table class="table">
        <thead>
            <tr>
                <th>Sistema</th>
                <th>Data</th>
                <th>Editar</th>
                <th>Remover</th>
            </tr>
        </thead>
        <tbody>
            <tr class="template hide" data-id-indicador-tecnico="">
                <td data-coluna-sistema></td>
                <td data-coluna-data></td>
                <td data-coluna-editar><button type="button" class="btn btn-info">Editar</button></td>
                <td data-coluna-remover><button type="button" class="btn btn-danger">Remover</button></td>
            </tr>
        </tbody>
    </table>
</div>
@section scripts {
    @Scripts.Render("~/bundles/scriptsIndicadoresTecnicos")
    <script type="text/javascript">
        var urlListarMedicoes = '@Url.Action("ListarMedicoes", "IndicadorTecnico")';
        var urlRemoverMedicao = '@Url.Action("RemoverMedicao", "IndicadorTecnico")';
        var urlCadastro = '@Url.Action("Cadastro", "IndicadorTecnico")';
    </script>
}