CentralEstatisticas/CentralEstatisticas/Controllers/IndicadorNegocioController.cs
using CentralEstatisticas.Business;
using CentralEstatisticas.Entidades.Dto.IndicadorNegocio;
using CentralEstatisticas.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace CentralEstatisticas.Controllers
{
    public class IndicadorNegocioController : BaseMvcController
    {
        private IndicadoresNegocioBusiness Business { get; set; }

        public IndicadorNegocioController()
        {
            Business = new IndicadoresNegocioBusiness();
        }

        public ViewResult Index()
        {
            return View(new ListaIndicadoresNegocioModel
            {
                ListaSistemas = new SistemaBusiness().Listar().Select(s => new SelectListItem { Value = s.Id.ToString(), Text = s.Nome })
            });
        }

        public ViewResult Cadastro(int? idMedicao)
        {
            if (idMedicao.HasValue)
            {
                Business.ObterMedicao(idMedicao.Value);
            }
            return View();
        }

        [HttpPost]
        public JsonResult ListarMedicoes(int idSistema)
        {
            return Json(new { Medicoes = Business.ListarMedicoes(idSistema) });
        }

        [HttpPost]
        public JsonResult SalvarMedicao(int? idMedicao, int idSistema, DateTime dataInicio, DateTime dataFim, 
            IEnumerable<IndicadorParaSalvarDto> listaIndicadores)
        {
            Business.SalvarMedicao(idMedicao, idSistema, dataInicio, dataFim, listaIndicadores);
            return ObterJsonSucessoPadrao();
        }

        public JsonResult RemoverMedicao(int idMedicao)
        {
            Business.RemoverMedicao(idMedicao);
            return ObterJsonSucessoPadrao();
        }
    }
}

CentralEstatisticas/CentralEstatisticas/Views/IndicadorNegocio/Cadastro.cshtml
@section scripts {
    @Scripts.Render("~/bundles/scriptsIndicadoresNegocio")
    <script type="text/javascript">
        var urlSalvarMedicao = '@Url.Action("SalvarMedicao", "IndicadorNegocio")';
    </script>
}

CentralEstatisticas/CentralEstatisticas/Views/IndicadorNegocio/Index.cshtml
@model CentralEstatisticas.Models.ListaIndicadoresNegocioModel
<div class="row">
    <form>
        <div class="form-group col-md-8">
            <label>Sistema</label>
            <select class="select2" type="text" data-filtro-sistema>
                <option value="">Selecione</option>
                @foreach (var sistema in Model.ListaSistemas)
                {
                    <option value="@sistema.Value">@sistema.Text</option>
                }
            </select>
        </div>
        <div class="col-md-4">
            <button class="btn btn-default" type="button" data-filtrar>Filtrar</button>
            <button class="btn btn-info" type="button" data-novo>Novo</button>
        </div>
    </form>
</div>
<div class="row">
    <table class="table">
        <thead>
            <tr>
                <th>Sistema</th>
                <th>Data Início</th>
                <th>Data Fim</th>
                <th>Editar</th>
                <th>Remover</th>
            </tr>
        </thead>
        <tbody>
            <tr class="template hide" data-id-indicador-negocio="">
                <td data-coluna-sistema></td>
                <td data-coluna-data-inicio></td>
                <td data-coluna-data-fim></td>
                <td data-coluna-editar><button type="button" class="btn btn-info">Editar</button></td>
                <td data-coluna-remover><button type="button" class="btn btn-danger">Remover</button></td>
            </tr>
        </tbody>
    </table>
</div>
@section scripts {
    @Scripts.Render("~/bundles/scriptsIndicadoresNegocio")
    <script type="text/javascript">
        var urlListarMedicoes = '@Url.Action("ListarMedicoes", "IndicadorNegocio")';
        var urlRemoverMedicao = '@Url.Action("RemoverMedicao", "IndicadorNegocio")';
        var urlCadastro = '@Url.Action("Cadastro", "IndicadorNegocio")';
    </script>
}